from django.urls import path

from tasks.views import (
    index, TaskListView,
    WorkerListView,
    WorkerDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDetailView,
    TaskDeleteView,
    TeamListView,
    TeamDetailView,
    WorkerCreateView,
    WorkerUpdateView,
    WorkerDeleteView,
    TeamCreateView,
    TeamUpdateView,
    TeamDeleteView,
    WorkerTaskListView,
    ProjectListView,
    ProjectDetailView,
    ProjectCreateView,
    ProjectUpdateView,
    ProjectDeleteView,
    ProjectTaskListView,
)

app_name = "tasks"

urlpatterns = [
    path("", index, name="index"),
    path("dashboard/", TaskListView.as_view(), name="task-list"),
    path("dashboard/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("dashboard/create/", TaskCreateView.as_view(), name="task-create"),
    path("dashboard/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("dashboard/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("teams/", TeamListView.as_view(), name="team-list"),
    path("teams/create/", TeamCreateView.as_view(), name="team-create"),
    path("teams/<int:pk>/update/", TeamUpdateView.as_view(), name="team-update"),
    path("teams/<int:pk>/delete/", TeamDeleteView.as_view(), name="team-delete"),
    path("teams/<int:pk>/", TeamDetailView.as_view(), name="team-detail"),
    path("members/", WorkerListView.as_view(), name="worker-list"),
    path("members/create/", WorkerCreateView.as_view(), name="worker-create"),
    path("members/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("members/<int:pk>/delete/", WorkerDeleteView.as_view(), name="worker-delete"),
    path("members/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("members/<int:pk>/tasks/", WorkerTaskListView.as_view(), name="worker-tasks"),
    path("project/", ProjectListView.as_view(), name="project-list"),
    path("project/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("project/create/", ProjectCreateView.as_view(), name="project-create"),
    path("project/<int:pk>/update/", ProjectUpdateView.as_view(), name="project-update"),
    path("project/<int:pk>/delete/", ProjectDeleteView.as_view(), name="project-delete"),
    path("project/<int:pk>/tasks/", ProjectTaskListView.as_view(), name="project-tasks"),
]