# Generated by Django 5.2.4 on 2025-07-29 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_remove_team_members_worker_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="worker",
            name="team",
        ),
        migrations.AddField(
            model_name="team",
            name="members",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
